#! /usr/bin/bash

function connect(){
		
		read -p "Enter DB Name: " name
           	
           	while true ;
           	do
		# if user want to return MainMenu to check NameDB 
		if  [[ $name =~ ^:[qQ]$ ]] ;then	
			exit
		elif [[ -d ../.db/$name ]] ;then 
			# connect DB
			# sudo: the -s option may be used to run a privileged shell.
			# sudo: the -D option may be used to run a command in a specific directory.
			#sudo -s cd ../.db/$name
			echo "DB *$name* Connected Successfully."
			# save name in variable to use in function of table
			nameDB=$name
			break
		else
			echo "DB *$name* Not Exist to Connect."
		fi
		      read -p "Please Re-Enter DB Name: " name
		done
		
		
		MenuTable

}

function MenuTable(){
	
	while true ;
      do
		select choice in "CREATE TABLE" "LIST TABLEs" "Re-Name TABLE" "INSERT TABLE" "UPDATE TABLE" "DELETE FROM TABLE" "DROP TABLE" "TRUNCATE TABLE" "SELECT TABLE" "EXIT TABLE" " EXIT DB"
		do 

				    case $REPLY in 
					  1)
					  	. ./ConfigTable/create
					  	break
					  ;;
					  2)
					  	echo "LIST TABLEs"
						. ./ConfigTable/list
						break
					  ;;
					  3)
					  	echo "Rename TABLE"
					  	source ./ConfigTable/rename
					  	break
					  ;;
					  4)
					         echo "INSERT TABLES"
					  	
					  	 . ./ConfigTable/insert
					  	 break
					  
					  ;;
					  5)
					  	echo "UPDATE DB"
					  	source ./ConfigTable/update
						break
					  ;;
					  6)
					  	echo "DELETE FROM TABLE"
					  	source ./ConfigTable/delete
					  	break
					  ;;
					  7)
					  	echo "DROP TABLE"
					  	source ./ConfigTable/drop
					  	break
					  ;;
					  8)
					  	echo "TRUNCATE TABLE"
					  	source ./ConfigTable/truncate
					  	break
					  ;;

                                          9)
					             echo "SELECT TABLE"
					  	. ./ConfigTable/selecttable
					  
					  ;;
					  10)
					  	echo "EXIT TABLE"
					  	continue
					  ;;
					  11)
					  	echo "EXIT DB"
					  	exit
					  ;;
					  *) 
						echo "PLease Select Valid number 1|2|3|4|5."
					  ;;
				    esac
		done 
	done
}
connect
