#! /usr/bin/bash

function rename(){
	read -p "Which DB Want to Re-Name? " name
	while true ; 
	do
		# if user want to return MainMenu to check NameDB 
		if  [[ $name =~ ^:[qQ]$ ]] ; then	
			exit
		elif [[ -d ../.db/"$name" ]] ;then
			echo "DB Name Can't Be Start with Special Char At least 2char."
			read -p "Enter New Name of DB? " newName
			if [[ "$newName" =~ ^[A-Za-z0-9]+[".""_"" ""-"]*[A-Za-z0-9]+$ ]] ; then 
			# rename DB
				mv ../.db/"$name" ../.db/"$newName"
			else
				echo "Invalid Name."
			fi
			
			break
		else
			echo "DB *$name* Not Exist"
		fi
		      read -p "Please Re-Enter DB Name: " name
	done
	

}
rename

